const http=require('http');const {URL}=require('url');const PORT=process.env.PORT||4000;
const b64url=s=>Buffer.from(s).toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
// Minimal GitHub OAuth (Authorization Code flow). Needs GITHUB_CLIENT_ID / GITHUB_CLIENT_SECRET.
async function githubOAuthStart(req,res){const clientId=process.env.GITHUB_CLIENT_ID;if(!clientId){res.writeHead(500,{'Content-Type':'text/plain'});return res.end('GitHub OAuth is not configured: set GITHUB_CLIENT_ID / GITHUB_CLIENT_SECRET on the backend.')}
  const redirectUri=`http://localhost:${PORT}/auth/github/callback`,url=`https://github.com/login/oauth/authorize?client_id=${encodeURIComponent(clientId)}&scope=repo&redirect_uri=${encodeURIComponent(redirectUri)}`;res.writeHead(302,{Location:url});res.end()}
async function githubOAuthCallback(req,res){const feOrigin=process.env.FRONTEND_ORIGIN||'http://localhost:3000';try{const clientId=process.env.GITHUB_CLIENT_ID,clientSecret=process.env.GITHUB_CLIENT_SECRET;if(!clientId||!clientSecret)throw Error('GitHub OAuth is not configured on the backend.');
    const code=new URL(req.url,`http://localhost:${PORT}`).searchParams.get('code');if(!code)throw Error('Missing OAuth code.');
    const tokenRes=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({client_id:clientId,client_secret:clientSecret,code})}),tokenData=await tokenRes.json();if(!tokenData.access_token)throw Error(tokenData.error_description||'GitHub did not return an access token.');
    const userRes=await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${tokenData.access_token}`,'User-Agent':'pit-wall',Accept:'application/vnd.github+json'}});if(!userRes.ok)throw Error('Failed to fetch GitHub user profile.');
    const user=await userRes.json(),payload=b64url(JSON.stringify({user:{login:user.login,avatar_url:user.avatar_url},token:tokenData.access_token}));
    res.writeHead(302,{Location:`${feOrigin}/?github_auth=${payload}`});res.end()
  }catch(e){res.writeHead(302,{Location:`${feOrigin}/?github_auth_error=${encodeURIComponent(e.message||'OAuth failed.')}`});res.end()}}
const mins=r=>Math.max(1,Math.round((new Date(r.updated_at)-new Date(r.run_started_at||r.created_at))/60000));const clean=s=>String(s||'').trim().replace(/^https?:\/\/(?:www\.)?github\.com\//i,'').replace(/^github\.com[/:]/i,'').replace(/\/$/,'');
async function scan(input,token=''){const m=clean(input).match(/^([^/\s]+)\/([^/\s#]+?)(?:\.git)?$/i);if(!m)throw Error('Enter a GitHub repository like owner/name.');const [owner,name]=[m[1],m[2]],h={'Accept':'application/vnd.github+json','User-Agent':'pit-wall'},auth=token.trim()||process.env.GITHUB_TOKEN||'';if(auth)h.Authorization=`Bearer ${auth}`;const get=async u=>{const r=await fetch(u,{headers:h});if(!r.ok)throw Error(r.status===404?'Repository not found or not public.':r.status===403?'GitHub rate limit reached. Add a GitHub token for more scans.':`GitHub returned ${r.status}.`);return r.json()};const runs=[];for(let page=1;page<=3;page++){const batch=(await get(`https://api.github.com/repos/${owner}/${name}/actions/runs?per_page=50&page=${page}`)).workflow_runs||[];runs.push(...batch);if(batch.length<50)break}const groups={};for(const run of runs){const jobs=(await get(`https://api.github.com/repos/${owner}/${name}/actions/runs/${run.id}/jobs?per_page=50`)).jobs||[];for(const job of jobs){const k=`${job.name}::${run.head_sha}`;(groups[k]||=[]).push({run,job})}}const found=[];for(const[k,items]of Object.entries(groups)){const fail=items.filter(x=>x.job.conclusion==='failure').sort((a,b)=>+new Date(a.run.created_at)-+new Date(b.run.created_at)),pass=items.filter(x=>x.job.conclusion==='success');if(fail.length&&pass.some(x=>+new Date(x.run.created_at)>+new Date(fail[0].run.created_at)))found.push({name:k.split('::')[0],wasted:mins(fail[0].run),count:fail.length,sha:fail[0].run.head_sha.slice(0,7),failedUrl:fail[0].run.html_url,jobId:fail[0].job.id})}const by={};found.forEach(f=>{(by[f.name]||={name:f.name,count:0,wasted:0,flakes:[]}).count+=f.count;by[f.name].wasted+=f.wasted;by[f.name].flakes.push(f)});return{repo:`${owner}/${name}`,totalRuns:runs.length,flakyCount:found.length,wastedMinutes:found.reduce((n,f)=>n+f.wasted,0),jobs:Object.values(by).sort((a,b)=>b.wasted-a.wasted)}}
// Fetches the tail of a failed job's log (last ~200 lines around the failure).
async function fetchLogTail(owner,name,jobId,token=''){const h={'Accept':'application/vnd.github+json','User-Agent':'pit-wall'},auth=token.trim()||process.env.GITHUB_TOKEN||'';if(auth)h.Authorization=`Bearer ${auth}`;const r=await fetch(`https://api.github.com/repos/${owner}/${name}/actions/jobs/${jobId}/logs`,{headers:h,redirect:'follow'});if(!r.ok)return'';const text=await r.text();return text.split('\n').slice(-200).join('\n').slice(0,12000)}

// Sends a log excerpt to Claude, asks for root-cause classification + a
// ready-to-file GitHub issue draft (title/body/optional diff), as JSON.
async function analyzeLog(jobName,repoFullName,logExcerpt){const key=process.env.GROQ_API_KEY;if(!key)throw Error('GROQ_API_KEY is not set on the backend.');
  if(!logExcerpt.trim())return{category:'other',explanation:'No log content was available (logs expire after 90 days on GitHub). Re-run right after a fresh failure to capture one.',issueTitle:`Flaky job: ${jobName}`,issueBody:`## Summary\n\n\`${jobName}\` in ${repoFullName} failed then passed on the same commit, but no log excerpt was available.`,suggestedDiff:null};
  const sys=`You are a senior CI reliability engineer. You're given the tail of a GitHub Actions log from a run that FAILED, on a commit where the exact same job later PASSED with no code changes (it's flaky, not a real regression).\n1. Classify the root cause as exactly one of: "timing/race condition", "network flakiness", "test ordering/shared state", "resource exhaustion", "external dependency", "other".\n2. Explain in 2-3 sentences, citing evidence from the log.\n3. Draft a GitHub issue: a short specific title, and a Markdown body with Summary / Evidence / Proposed Fix sections.\n4. If you can identify a plausible code fix (retry+backoff, explicit wait instead of sleep, test isolation), sketch it as a small fenced diff; otherwise set suggestedDiff to null.\nRespond with ONLY raw JSON, no markdown fences: {"category":"...","explanation":"...","issueTitle":"...","issueBody":"...","suggestedDiff":"..."|null}`;
  const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:'openai/gpt-oss-120b',max_tokens:1500,response_format:{type:'json_object'},messages:[{role:'system',content:sys},{role:'user',content:`Repo: ${repoFullName}\nJob name: ${jobName}\n\nLog excerpt:\n\`\`\`\n${logExcerpt}\n\`\`\``}]})});
  if(!r.ok){const errBody=await r.text().catch(()=>'');throw Error(`Groq API returned ${r.status}: ${errBody.slice(0,300)}`)}
  const data=await r.json(),raw=data.choices?.[0]?.message?.content||'{}';
  try{return JSON.parse(raw.replace(/^```json\s*|```\s*$/g,'').trim())}catch{return{category:'other',explanation:'Groq returned a response that could not be parsed as JSON.',issueTitle:`Flaky job: ${jobName}`,issueBody:raw.slice(0,4000),suggestedDiff:null}}
}

http.createServer((req,res)=>{res.setHeader('Access-Control-Allow-Origin',process.env.FRONTEND_ORIGIN||'http://localhost:3000');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}
  if(req.method==='POST'&&req.url==='/api/scan'){let raw='';req.on('data',c=>raw+=c);return req.on('end',async()=>{try{const b=JSON.parse(raw||'{}'),out=await scan(b.repo,b.token||'');res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(out))}catch(e){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message||'Scan failed.'}))}})}
  if(req.method==='POST'&&req.url==='/api/analyze'){let raw='';req.on('data',c=>raw+=c);return req.on('end',async()=>{try{const b=JSON.parse(raw||'{}'),m=clean(b.repo).match(/^([^/\s]+)\/([^/\s#]+?)(?:\.git)?$/i);if(!m)throw Error('Enter a GitHub repository like owner/name.');if(!b.jobId)throw Error('jobId is required.');const [owner,name]=[m[1],m[2]],log=await fetchLogTail(owner,name,b.jobId,b.token||''),analysis=await analyzeLog(b.jobName||'unknown job',`${owner}/${name}`,log);res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({analysis}))}catch(e){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message||'Analysis failed.'}))}})}
  if(req.method==='GET'&&req.url==='/auth/github')return githubOAuthStart(req,res)
  if(req.method==='GET'&&req.url.startsWith('/auth/github/callback'))return githubOAuthCallback(req,res)
  res.writeHead(404);res.end('Not found')
}).listen(PORT,()=>console.log(`Pit Wall backend running at http://localhost:${PORT}`));