'use client'
import { useState } from 'react'
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip } from 'recharts'
const chart=[{d:'May 28',v:2},{d:'Jun 4',v:4},{d:'Jun 11',v:3},{d:'Jun 18',v:7},{d:'Jun 25',v:5},{d:'Jul 2',v:9},{d:'Jul 9',v:8},{d:'Jul 16',v:13}]
const jobs=[['test / integration','13 flakes','4h 12m','up'],['lint / eslint','8 flakes','2h 48m','up'],['test / unit (node 20)','5 flakes','1h 06m','down'],['build / linux','3 flakes','38m','up']]
export default function Dashboard({repo,data,token}:{repo:string,data?:any,token?:string}) { const [selected,setSelected]=useState(0); const [issue,setIssue]=useState(false); const [analysis,setAnalysis]=useState<any>(); const [analyzing,setAnalyzing]=useState(false); const [analyzeError,setAnalyzeError]=useState(''); const liveJobs=data?data.jobs:jobs; const job=liveJobs[selected]||jobs[0]
async function generateIssue(){setIssue(true);setAnalysis(undefined);setAnalyzeError('');const jobName=job.name||job[0];const jobId=job.flakes?.[0]?.jobId;if(!jobId){setAnalyzeError('No live job ID available for this entry (demo data), so AI analysis can\'t run.');return}
  setAnalyzing(true);try{const base=process.env.NEXT_PUBLIC_API_URL||'';const r=await fetch(`${base}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repo,jobId,jobName,token})}),d=await r.json();if(!r.ok)throw Error(d.error||'Analysis failed.');setAnalysis(d.analysis)}catch(e:any){setAnalyzeError(e.message)}finally{setAnalyzing(false)}}
return <div className="dashboard"><header className="dash-head"><div><div className="crumb">OVERVIEW <span>/</span> <b>{repo}</b></div><h2>Good morning, Jordan <span>✦</span></h2><p>Here’s what your CI has been hiding.</p></div><div className="actions"><button className="ghost">↻ &nbsp; Re-scan</button><button className="primary small">Connect repo</button></div></header>
<div className="stats"><div className="stat hot"><small>WASTED THIS MONTH <span>ⓘ</span></small><strong>{data?`${Math.floor(data.wastedMinutes/60)}h ${data.wastedMinutes%60}m`:'8h 44m'}</strong><b>≈ ${(data?(data.wastedMinutes*.008).toFixed(2):'4.19')} <span>at Linux rates</span></b><label>LIVE SCAN <i>from GitHub Actions</i></label></div><div className="stat"><small>FLAKY JOBS</small><strong>{data?.flakyCount??29}</strong><b>detected in recent runs</b><label>LIVE <i>same commit reruns</i></label></div><div className="stat"><small>RUNS ANALYZED</small><strong>{data?.totalRuns?.toLocaleString()??'1,284'}</strong><b>last 30 days</b><label className="neutral">GitHub Actions <i>history</i></label></div></div>
<section className="content-grid"><div className="panel leaderboard"><div className="panel-head"><div><h3>Flakiest jobs</h3><p>Ranked by wasted CI time · live GitHub scan</p></div><button className="filter">Last 30 days⌄</button></div><div className="table-head"><span>JOB</span><span>FLAKES</span><span>WASTED</span><span>TREND</span></div>{liveJobs.slice(0,4).map((x:any,i:number)=>{const n=x.name||x[0],c=x.count||x[1],w=x.wasted?`${Math.floor(x.wasted/60)}h ${x.wasted%60}m`:x[2];return <button className={'job-row '+(selected===i?'selected':'')} onClick={()=>{setSelected(i);setIssue(false);setAnalysis(undefined);setAnalyzeError('')}} key={n}><span className="job-name"><b>{i+1}</b><i className={'status s'+i}/><code>{n}</code></span><span>{c}</span><span>{w}</span><span className="up">↗ live</span></button>})}<div className="panel-foot">Showing top {Math.min(4,liveJobs.length)} of {data?.flakyCount??29} flaky jobs</div></div>
<div className="panel chart-panel"><div className="panel-head"><div><h3>{job[0]}</h3><p>Flakes over time</p></div><span className="badge">● NEEDS ATTENTION</span></div><div className="chart"><ResponsiveContainer width="100%" height={210}><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f04444" stopOpacity={.3}/><stop offset="100%" stopColor="#f04444" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fill:'#77808e',fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#77808e',fontSize:11}}/><Tooltip contentStyle={{background:'#20242c',border:'1px solid #343a45',borderRadius:8,color:'#fff'}}/><Area type="monotone" dataKey="v" stroke="#ff5757" strokeWidth={2} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div><div className="cause"><div className="cause-icon">⚡</div><div><small>AI ROOT-CAUSE ANALYSIS</small><p>{analysis?<><b>{analysis.category}.</b> {analysis.explanation}</>:<><b>Likely timing / race condition.</b> Tests intermittently compete for a shared port during parallel execution. The failure disappears on rerun because the competing process has already released its lock. <i style={{fontStyle:'normal',color:'#697280'}}>(placeholder — generate the issue below for a real analysis of this job)</i></>}</p></div></div><button className="issue-btn" onClick={generateIssue} disabled={analyzing}>✦ {analyzing?'Analyzing logs…':issue?'Regenerate':'Generate GitHub Issue'} <span>→</span></button>{issue&&<div className="issue">{analyzing&&<div><b>Fetching logs and asking the AI for a root cause…</b></div>}{!analyzing&&analyzeError&&<div><b style={{color:'#ff7777'}}>{analyzeError}</b></div>}{!analyzing&&analysis&&<><div><b>{analysis.issueTitle}</b><button onClick={()=>navigator.clipboard?.writeText(analysis.issueBody)}>Copy markdown</button></div><pre>{analysis.issueBody}</pre>{analysis.suggestedDiff&&<pre>{analysis.suggestedDiff}</pre>}<a href={'https://github.com/'+repo+'/issues/new?title='+encodeURIComponent(analysis.issueTitle)+'&body='+encodeURIComponent(analysis.issueBody)} target="_blank">Open in GitHub ↗</a></>}</div>}</div></section></div> }
